name: RSI 1H Scanner (diag)

on:
  workflow_dispatch:       # 수동 실행만. (원인 파악 끝나면 스케줄 다시 켭니다)

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: rsi-scan
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Show workspace & versions
        run: |
          echo "::group::Workspace"
          pwd
          ls -la
          echo "::endgroup::"
          echo "::group::Python/Pip"
          python -V
          python -m pip -V || true
          echo "::endgroup::"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python - <<'PY'
import sys
try:
    import aiohttp
    print("IMPORT_OK aiohttp", aiohttp.__version__)
except Exception as e:
    print("IMPORT_FAIL", e)
    sys.exit(1)
PY

      - name: Network check
        run: |
          echo "Binance ping:"
          curl -s -S -w "\nHTTP %{http_code}\n" https://api.binance.com/api/v3/ping || true
          echo "CoinGecko ping:"
          curl -s -S -w "\nHTTP %{http_code}\n" https://api.coingecko.com/api/v3/ping || true

      # 스캐너는 '소프트 실행': 실패해도 잡은 성공으로 유지(원인 파악이 목적)
      - name: Run RSI scanner (soft)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -x
          python rsi_scanner_binance_1h_v4_1.py --min-volume 5000000 --quotes USDT,FDUSD --skip-mcap --timeout 30 || true
