name: RSI 1H Scanner

on:
  schedule:
    - cron: "5 * * * *"   # 매시 05분(UTC) 실행
  workflow_dispatch:       # 수동 실행 버튼

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: rsi-scan
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Network check
        run: |
          echo "Binance ping:"
          curl -s -S -w "\nHTTP %{http_code}\n" https://api.binance.com/api/v3/ping || true
          echo "CoinGecko ping:"
          curl -s -S -w "\nHTTP %{http_code}\n" https://api.coingecko.com/api/v3/ping || true

      # 시총 호출 불안정 대비: --skip-mcap 사용(거래대금 정렬로 자동 대체)
      - name: Run RSI scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python rsi_scanner_binance_1h_v4_1.py --min-volume 5000000 --quotes USDT,FDUSD --skip-mcap --timeout 30
