name: RSI 1H Scanner (diag2)

on:
  workflow_dispatch:   # 수동 실행만

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show tree
        run: |
          echo "PWD:"; pwd
          echo "TREE:"; ls -la

      # 스크립트가 저장소 '루트'에 있는지 확인
      - name: Ensure script exists
        run: |
          test -f rsi_scanner_binance_1h_v4_1.py || (echo "ERROR: SCRIPT_NOT_FOUND at repo root" && exit 1)

      # 의존성 설치 (requirements 없이도 동작하도록 최소만)
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Import check
        run: python -c "import aiohttp,sys; print('IMPORT_OK aiohttp', aiohttp.__version__)"

      - name: Network check
        run: |
          echo "Binance ping:"; curl -s -S -w "\nHTTP %{http_code}\n" https://api.binance.com/api/v3/ping || true

      - name: Run scanner (skip mcap)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python rsi_scanner_binance_1h_v4_1.py --min-volume 5000000 --quotes USDT,FDUSD --skip-mcap --timeout 30
